--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-04-22 00:52:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16428)
-- Name: contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contact (
    id integer NOT NULL,
    title text NOT NULL,
    content text NOT NULL
);


ALTER TABLE public.contact OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16431)
-- Name: contact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 24598)
-- Name: contactadmin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contactadmin (
    id integer NOT NULL,
    title text NOT NULL,
    content text NOT NULL
);


ALTER TABLE public.contactadmin OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 24601)
-- Name: contactadmin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.contactadmin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contactadmin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 24623)
-- Name: login; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.login (
    id integer NOT NULL,
    email text NOT NULL,
    password text NOT NULL
);


ALTER TABLE public.login OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 24628)
-- Name: login_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.login ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16410)
-- Name: pricingbase; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pricingbase (
    id integer NOT NULL,
    title text NOT NULL,
    content text NOT NULL
);


ALTER TABLE public.pricingbase OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16413)
-- Name: pricing1_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pricingbase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pricing1_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    CYCLE
);


--
-- TOC entry 225 (class 1259 OID 24576)
-- Name: pricingbaseadmin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pricingbaseadmin (
    id integer NOT NULL,
    title text NOT NULL,
    content text NOT NULL
);


ALTER TABLE public.pricingbaseadmin OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24579)
-- Name: pricingBaseadmin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pricingbaseadmin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."pricingBaseadmin_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16419)
-- Name: pricingother; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pricingother (
    id integer NOT NULL,
    title text NOT NULL,
    content text NOT NULL
);


ALTER TABLE public.pricingother OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16422)
-- Name: pricingOther_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pricingother ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."pricingOther_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 24587)
-- Name: pricingotheradmin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pricingotheradmin (
    id integer NOT NULL,
    title text NOT NULL,
    content text NOT NULL
);


ALTER TABLE public.pricingotheradmin OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24590)
-- Name: pricingOtheradmin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pricingotheradmin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."pricingOtheradmin_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services (
    id integer NOT NULL,
    title text NOT NULL,
    content text NOT NULL
);


ALTER TABLE public.services OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16437)
-- Name: servicesadmin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.servicesadmin (
    id integer NOT NULL,
    title text NOT NULL,
    content text NOT NULL
);


ALTER TABLE public.servicesadmin OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16440)
-- Name: servicesAdmin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.servicesadmin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."servicesAdmin_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16404)
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4895 (class 0 OID 16428)
-- Dependencies: 221
-- Data for Name: contact; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contact (id, title, content) FROM stdin;
0	Tutvustus	Minu nimi on Galina. Pakun raamatupidamisteenuseid mikro- ja väikeettevõtetele. Professionaalne, usaldusväärne ja kliendikeskne raamatupidamine aitab teie ettevõttel jälgida finantsolukorda ja seekaudu teha teadlike äriotsuseid, mis aitavad tagada ettevõtte majandusliku jätkusuutlikkuse. Olen pühendunud oma iga kliendi edule ning usun, et professionaalne lähenemine ja individuaalne teenindus aitavad minu koostööpartneritel keskenduda oma äritegevuse olulistele aspektidele ning saavutada pikaajaline edu ja kasv.\n\nOlen finantsarvestuse valdkonnas töötanud 28 aastat. Oman Tallinna Tehnikakõrgkooli kõrgharidust majandusarvestuse alal ning raamatupidaja tase 5 kutsetunnistust. Suhtlen teiega eesti ja vene keeles.
\.


--
-- TOC entry 4903 (class 0 OID 24598)
-- Dependencies: 229
-- Data for Name: contactadmin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contactadmin (id, title, content) FROM stdin;
0	Tutvustus	Minu nimi on Galina. Pakun raamatupidamisteenuseid mikro- ja väikeettevõtetele. Professionaalne, usaldusväärne ja kliendikeskne raamatupidamine aitab teie ettevõttel jälgida finantsolukorda ja seekaudu teha teadlike äriotsuseid, mis aitavad tagada ettevõtte majandusliku jätkusuutlikkuse. Olen pühendunud oma iga kliendi edule ning usun, et professionaalne lähenemine ja individuaalne teenindus aitavad minu koostööpartneritel keskenduda oma äritegevuse olulistele aspektidele ning saavutada pikaajaline edu ja kasv.\n\nOlen finantsarvestuse valdkonnas töötanud 28 aastat. Oman Tallinna Tehnikakõrgkooli kõrgharidust majandusarvestuse alal ning raamatupidaja tase 5 kutsetunnistust. Suhtlen teiega eesti ja vene keeles.
\.


--
-- TOC entry 4905 (class 0 OID 24623)
-- Dependencies: 231
-- Data for Name: login; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.login (id, email, password) FROM stdin;
3	galina	$2b$10$20p4R.wPz842G5OQ0SmuHu6FiEtEuRw7wn7bEZNulusLaQoiDf0oq
\.


--
-- TOC entry 4891 (class 0 OID 16410)
-- Dependencies: 217
-- Data for Name: pricingbase; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pricingbase (id, title, content) FROM stdin;
0	1-10	45
1	11-20	55
2	21-30	65
3	31-40	75
4	41-50	85
5	51-60	95
6	61-70	105
7	71-80	115
8	81-90	125
9	91-99	135
10	al. 100	kokkuleppel
\.


--
-- TOC entry 4899 (class 0 OID 24576)
-- Dependencies: 225
-- Data for Name: pricingbaseadmin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pricingbaseadmin (id, title, content) FROM stdin;
0	1-10	45
1	11-20	55
2	21-30	65
3	31-40	75
4	41-50	85
5	51-60	95
6	61-70	105
7	71-80	115
8	81-90	125
9	91-99	135
10	al. 100	kokkuleppel
\.


--
-- TOC entry 4893 (class 0 OID 16419)
-- Dependencies: 219
-- Data for Name: pricingother; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pricingother (id, title, content) FROM stdin;
0	Programmi lisakasutaja tasu kuus (kliendi võimalus sisestada müügiarveid raamatupidamise programmi)	0 €/tk
1	Müügiarve koostamine ja edastamine	5 €/tk
2	Koondarve koostamine	10 €/tk
3	Deklaratsiooni, INF jne esitamine Maksu- ja Tolliametile	5 €/tk
4	Töötaja registreerimine või kande muutmine TÖR-s	5 €/tk
5	Palgaarvestus töötaja kohta koos TSD esitamisega	10 €/tk
6	Palgaarvestus töötaja kohta koos TSD esitamisega	7 €/tk
7	Töövõimetuslehe esitamine Eesti Haigekassale	5 €/tk
8	Kuluaruande koostamine	al 10 €/tk
9	Ettevõtte lisa pangakonto lisatasu	10 €/tk
10	Kassaorderi koostamine	1 €/tk
11	Lähetusaruande koostamine	10 €/tk
12	Dokumendi digitaliseerimine	0.48 €/tk
13	Maksekorralduse ettevalmistamine	1 €/tk
14	Pangaülekande sooritamne	1 €/tk
15	Töölepingu koostamine	al 10 €/tk
16	Hinnapakkumise koostamine	 al 10 €/tk
17	Statistikaaruande koostamine	 al 10 €/tk
18	Kirja, tõendi jms koostamine	7 €/tk
19	Põhivara arvelevõtmine või eemaldamine põhivara nimekirjast	2 €/tk
20	Raamatupidamise aastaaruande koostamine mikroettevõttele	al 50 €/tk
21	Raamatupidamise aastaaruande koostamine väikeettevõttele	al 100 €/tk
22	Kasumiaruande koostamine ja väljastamine kuu lõikes	2 €/tk
23	Bilansi koostamine ja väljastamine kuu lõikes	2 €/tk
24	Eelmise perioodi korrastamine	35 €/tund
25	Raamatupidamise konsultatsioon	35 €/tund
\.


--
-- TOC entry 4901 (class 0 OID 24587)
-- Dependencies: 227
-- Data for Name: pricingotheradmin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pricingotheradmin (id, title, content) FROM stdin;
0	Programmi lisakasutaja tasu kuus (kliendi võimalus sisestada müügiarveid raamatupidamise programmi)	0 €/tk
1	Müügiarve koostamine ja edastamine	5 €/tk
2	Koondarve koostamine	10 €/tk
3	Deklaratsiooni, INF jne esitamine Maksu- ja Tolliametile	5 €/tk
4	Töötaja registreerimine või kande muutmine TÖR-s	5 €/tk
5	Palgaarvestus töötaja kohta koos TSD esitamisega	10 €/tk
6	Palgaarvestus töötaja kohta koos TSD esitamisega	7 €/tk
7	Töövõimetuslehe esitamine Eesti Haigekassale	5 €/tk
8	Kuluaruande koostamine	al 10 €/tk
9	Ettevõtte lisa pangakonto lisatasu	10 €/tk
10	Kassaorderi koostamine	1 €/tk
11	Lähetusaruande koostamine	10 €/tk
12	Dokumendi digitaliseerimine	0.48 €/tk
13	Maksekorralduse ettevalmistamine	1 €/tk
14	Pangaülekande sooritamne	1 €/tk
15	Töölepingu koostamine	al 10 €/tk
16	Hinnapakkumise koostamine	 al 10 €/tk
17	Statistikaaruande koostamine	 al 10 €/tk
18	Kirja, tõendi jms koostamine	7 €/tk
19	Põhivara arvelevõtmine või eemaldamine põhivara nimekirjast	2 €/tk
20	Raamatupidamise aastaaruande koostamine mikroettevõttele	al 50 €/tk
21	Raamatupidamise aastaaruande koostamine väikeettevõttele	al 100 €/tk
22	Kasumiaruande koostamine ja väljastamine kuu lõikes	2 €/tk
23	Bilansi koostamine ja väljastamine kuu lõikes	2 €/tk
24	Eelmise perioodi korrastamine	35 €/tund
25	Raamatupidamise konsultatsioon	35 €/tund
\.


--
-- TOC entry 4889 (class 0 OID 16399)
-- Dependencies: 215
-- Data for Name: services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services (id, title, content) FROM stdin;
0	Raamatupidamine	Osutan raamatupidamise teenust mikro- ja väikeettevõtetele.\n\nMikroettevõte on osaühing, mille näitajad vastavad aruandeaasta bilansipäeval kõikidele järgmistele tingimustele: varad kokku kuni 175 000 eurot, kohustised ei ole suuremad kui omakapital, üks osanik, kes on ka juhatuse liige ja mille müügitulu on aruandeaastal kuni 50 000 eurot.\nVäikeettevõte on äriühing, mille müügitulu on üle 8 miljoni euro, aruande aasta bilansipäeval on varasid kokku üle 4 miljoni euro või keskmine töötajate arv 50 inimest.\nKoostöös minuga on raamatupidamine internetipõhine ja paberivaba. Ettevõtte Gala RMP OÜ kasutab raamatupidamisprogramme MeritAktiva ja MeritPalk https://www.merit.ee/ ning teeb koostööd CostPocketiga https://costpocket.com/et. MeritAktiva võimaldab müügiarve koostamist ja edastamist e-arvena ja/või meili teel, liidesed pankadega võimaldavad maksekorralduse saatmist ja pangaväljavõte importi (Swedbank, LHV, SEB). Töötades CostPocketiga ei pea varundama tšekke/ ostuarveid eraldi kaustade vahel, vaid pildistades on need aktsepteeritavad kuludokumendid, mida saab edastada otse raamatupidamisprogrammi ning seal säilitada.
1	Majandusaasta aruanne	Aitan teid majandusaasta aruande koostamisel ja esitamisel. Ettevõtte majandusaasta aruanne on oluline dokument, mis annab ülevaate ettevõtte finantsseisust ja käekäigust kindlal perioodil. Aruandes esitatakse üksikasjalikult ettevõtte finantstulemused, sealhulgas müügitulu, kulud, kasum või kahjum, varad, kohustused jne. Majandusaastaaruande peab esitama äriregistrile, kes kontrollib majandustegevuse vastavust seaduses määratletule. Aruanded on avalikult kättesaadav konkurentidele, partneritele ning kõigile huvilistele.
2	Maksualane nõustamine ja konsultatsioon	Nõustan ja konsulteerin maksudega seotud küsimustes. Nõustamine enne tehingute tegemist aitab ettevõtjal vältida võimalikke maksuriske ja tagada, et nad kasutavad ära võimalikud maksusoodustused ning optimeerivad oma maksukohustusi seaduslikult. Saan teid aidata raamatupidamisega seotud küsimustes, töötasude arvestamisel ja maksude teemadel. Püsikliendile on konsultatsioonid tasuta ühe tunni ulatuses kuus.
\.


--
-- TOC entry 4897 (class 0 OID 16437)
-- Dependencies: 223
-- Data for Name: servicesadmin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.servicesadmin (id, title, content) FROM stdin;
0	Raamatupidamine	Osutan raamatupidamise teenust mikro- ja väikeettevõtetele.\n\nMikroettevõte on osaühing, mille näitajad vastavad aruandeaasta bilansipäeval kõikidele järgmistele tingimustele: varad kokku kuni 175 000 eurot, kohustised ei ole suuremad kui omakapital, üks osanik, kes on ka juhatuse liige ja mille müügitulu on aruandeaastal kuni 50 000 eurot.\nVäikeettevõte on äriühing, mille müügitulu on üle 8 miljoni euro, aruande aasta bilansipäeval on varasid kokku üle 4 miljoni euro või keskmine töötajate arv 50 inimest.\nKoostöös minuga on raamatupidamine internetipõhine ja paberivaba. Ettevõtte Gala RMP OÜ kasutab raamatupidamisprogramme MeritAktiva ja MeritPalk https://www.merit.ee/ ning teeb koostööd CostPocketiga https://costpocket.com/et. MeritAktiva võimaldab müügiarve koostamist ja edastamist e-arvena ja/või meili teel, liidesed pankadega võimaldavad maksekorralduse saatmist ja pangaväljavõte importi (Swedbank, LHV, SEB). Töötades CostPocketiga ei pea varundama tšekke/ ostuarveid eraldi kaustade vahel, vaid pildistades on need aktsepteeritavad kuludokumendid, mida saab edastada otse raamatupidamisprogrammi ning seal säilitada.
1	Majandusaasta aruanne	Aitan teid majandusaasta aruande koostamisel ja esitamisel. Ettevõtte majandusaasta aruanne on oluline dokument, mis annab ülevaate ettevõtte finantsseisust ja käekäigust kindlal perioodil. Aruandes esitatakse üksikasjalikult ettevõtte finantstulemused, sealhulgas müügitulu, kulud, kasum või kahjum, varad, kohustused jne. Majandusaastaaruande peab esitama äriregistrile, kes kontrollib majandustegevuse vastavust seaduses määratletule. Aruanded on avalikult kättesaadav konkurentidele, partneritele ning kõigile huvilistele.
2	Maksualane nõustamine ja konsultatsioon	Nõustan ja konsulteerin maksudega seotud küsimustes. Nõustamine enne tehingute tegemist aitab ettevõtjal vältida võimalikke maksuriske ja tagada, et nad kasutavad ära võimalikud maksusoodustused ning optimeerivad oma maksukohustusi seaduslikult. Saan teid aidata raamatupidamisega seotud küsimustes, töötasude arvestamisel ja maksude teemadel. Püsikliendile on konsultatsioonid tasuta ühe tunni ulatuses kuus.
\.


--
-- TOC entry 4912 (class 0 OID 0)
-- Dependencies: 222
-- Name: contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contact_id_seq', 62, true);


--
-- TOC entry 4913 (class 0 OID 0)
-- Dependencies: 230
-- Name: contactadmin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contactadmin_id_seq', 1, false);


--
-- TOC entry 4914 (class 0 OID 0)
-- Dependencies: 232
-- Name: login_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.login_id_seq', 3, true);


--
-- TOC entry 4915 (class 0 OID 0)
-- Dependencies: 218
-- Name: pricing1_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pricing1_id_seq', 110, true);


--
-- TOC entry 4916 (class 0 OID 0)
-- Dependencies: 226
-- Name: pricingBaseadmin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."pricingBaseadmin_id_seq"', 31, true);


--
-- TOC entry 4917 (class 0 OID 0)
-- Dependencies: 220
-- Name: pricingOther_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."pricingOther_id_seq"', 69, true);


--
-- TOC entry 4918 (class 0 OID 0)
-- Dependencies: 228
-- Name: pricingOtheradmin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."pricingOtheradmin_id_seq"', 10, true);


--
-- TOC entry 4919 (class 0 OID 0)
-- Dependencies: 224
-- Name: servicesAdmin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."servicesAdmin_id_seq"', 90, true);


--
-- TOC entry 4920 (class 0 OID 0)
-- Dependencies: 216
-- Name: services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_id_seq', 291, true);


--
-- TOC entry 4735 (class 2606 OID 16455)
-- Name: contact contact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contact
    ADD CONSTRAINT contact_pkey PRIMARY KEY (id);


--
-- TOC entry 4743 (class 2606 OID 24608)
-- Name: contactadmin contactadmin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contactadmin
    ADD CONSTRAINT contactadmin_pkey PRIMARY KEY (id);


--
-- TOC entry 4745 (class 2606 OID 24635)
-- Name: login login_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.login
    ADD CONSTRAINT login_pkey PRIMARY KEY (id);


--
-- TOC entry 4731 (class 2606 OID 16453)
-- Name: pricingbase pricingBase_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pricingbase
    ADD CONSTRAINT "pricingBase_pkey" PRIMARY KEY (id);


--
-- TOC entry 4739 (class 2606 OID 24586)
-- Name: pricingbaseadmin pricingBaseadmin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pricingbaseadmin
    ADD CONSTRAINT "pricingBaseadmin_pkey" PRIMARY KEY (id);


--
-- TOC entry 4733 (class 2606 OID 16451)
-- Name: pricingother pricingOther_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pricingother
    ADD CONSTRAINT "pricingOther_pkey" PRIMARY KEY (id);


--
-- TOC entry 4741 (class 2606 OID 24597)
-- Name: pricingotheradmin pricingOtheradmin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pricingotheradmin
    ADD CONSTRAINT "pricingOtheradmin_pkey" PRIMARY KEY (id);


--
-- TOC entry 4737 (class 2606 OID 16447)
-- Name: servicesadmin servicesAdmin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.servicesadmin
    ADD CONSTRAINT "servicesAdmin_pkey" PRIMARY KEY (id);


--
-- TOC entry 4729 (class 2606 OID 16449)
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


-- Completed on 2024-04-22 00:52:16

--
-- PostgreSQL database dump complete
--

